#!/usr/bin/env python3
"""
Checks the engine's runtime .syx bank loader (src/dsp/syx_bank.h) and the Bank / A-B / Program controls.

    python tools/test_bank_loader.py        (needs tools/FactoryBackUpDoResetAfter.syx; exit code 0 = all pass)

1. Parity: the factory dump decoded by the C loader equals the built-in presets.h bank in every float
   (presets.h is generated by tools/extracts_presets.py from the same dump; this pins the C port to it).
2. Scanning: *.syx files are loaded in case-insensitive alphabetical order; single-program dumps and junk
   are skipped; other extensions are ignored.
3. Names: a dump with stored 12-character names shows them ("A.11 Trancey" style names are kept as is,
   plain names get the code prepended); a dump without names labels presets by code ("A.11").
4. Selection: bank_file / bank_side / program select the right preset through the parameter API.
6. Host API: through the same v2 entry points the Schwung host calls (create with a module folder,
   set/get strings): live chain_params (Bank options = file names, Category, Program), the Banks page
   item list, Category/Program/preset selection and names, and ui_hierarchy identical to module.json.
5. Your banks: every .syx in the repo's banks/ folder is scanned as the module would; each loaded bank is
   cross-checked program by program against tools/extracts_presets.py, and skipped files are listed.
"""
import contextlib
import io
import json
import ctypes
import os
import shutil
import sys
import tempfile

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import calibrate_dsp as cal  # noqa: E402
from extracts_presets import FX_FIELDS, TIMBRE_FIELDS, load_programs, parse_program, unpack_7to8  # noqa: E402

FACTORY = os.path.join(HERE, "FactoryBackUpDoResetAfter.syx")
USER_BANKS = os.path.join(cal.ROOT, "banks")
FAILS = []


def check(cond, what):
    print(("  PASS  " if cond else "  FAIL  ") + what)
    if not cond:
        FAILS.append(what)


def pack_7to8(raw):
    """Inverse of unpack_7to8: 7 data bytes -> [MSB bits][7 bytes with bit 7 cleared]."""
    out = bytearray()
    for i in range(0, len(raw), 7):
        chunk = raw[i:i + 7]
        out.append(sum(1 << j for j, b in enumerate(chunk) if b & 0x80))
        out.extend(b & 0x7F for b in chunk)
    return bytes(out)


def with_names(dump, names):
    """The factory dump with program names written into bytes 0..11 of the given programs."""
    start, end = dump.find(b"\xF0"), dump.rfind(b"\xF7")
    raw = bytearray(unpack_7to8(dump[start + 5:end]))
    for idx, name in names.items():
        raw[idx * 254: idx * 254 + 12] = name.ljust(12)[:12].encode("ascii")
    return dump[:start + 5] + pack_7to8(raw) + b"\xF7"


def user_banks(fptr):
    """Scan the repo's banks/ folder with a separate engine copy, as the module would at start-up."""
    files = sorted((f for f in os.listdir(USER_BANKS) if f.lower().endswith(".syx")), key=str.lower) if os.path.isdir(USER_BANKS) else []
    print(f"\nYour banks ({USER_BANKS}, {len(files)} .syx files):")
    if not files:
        print("  (none)")
        return
    tmp = tempfile.mkdtemp(prefix="tinyk_userbanks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))  # fresh library: its bank table starts empty
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        n = lib.tinyk_bank_scan(USER_BANKS.encode())
        loaded = [lib.tinyk_bank_name(b).decode() for b in range(1, n + 1)]
        skipped = [f for f in files if os.path.splitext(f)[0] not in loaded]
        for b, name in enumerate(loaded, 1):
            with contextlib.redirect_stdout(io.StringIO()):
                ref = [parse_program(i, prog) for i, prog in enumerate(load_programs(os.path.join(USER_BANKS, name + ".syx")))]
            worst, labels, named, vocoders = 0.0, [], 0, 0
            for i in range(128):
                t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                fx = np.zeros(len(FX_FIELDS), np.float32)
                lab = ctypes.create_string_buffer(32)
                vm = lib.tinyk_bank_preset(b, i, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), lab, 32)
                want = np.array([ref[i]["t1"][f] for f in TIMBRE_FIELDS] + [ref[i]["t2"][f] for f in TIMBRE_FIELDS]
                                + [ref[i]["fx"][f] for f in FX_FIELDS], np.float32)
                worst = max(worst, float(np.abs(np.concatenate([t1, t2, fx]) - want).max()))
                worst = max(worst, 0.0 if vm == int(ref[i]["voice_mode"]) else 1.0)
                labels.append(lab.value.decode())
                named += len(labels[-1]) > 4
                vocoders += not ref[i]["data_valid"]
            check(worst <= 1e-6, f"bank {b} {name!r}: 128 programs, {named} named, {vocoders} vocoder; "
                                 f"matches extracts_presets.py (max diff {worst:.1e}); e.g. {labels[0]!r}, {labels[1]!r}, {labels[64]!r}")
        for f in skipped:
            print(f"  skip  {f} ({os.path.getsize(os.path.join(USER_BANKS, f))} bytes: not a 128-program bank dump)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def host_api():
    """The module as the host drives it: v2_create_instance(module_dir) scans <module_dir>/banks."""
    print("\nHost API (v2 entry points):")
    tmp = tempfile.mkdtemp(prefix="tinyk_hostapi_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_v2_create.argtypes = [ctypes.c_char_p]
        lib.tinyk_v2_set.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
        lib.tinyk_v2_get.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        module_dir = os.path.join(tmp, "module")
        os.makedirs(os.path.join(module_dir, "banks"))
        dump = open(FACTORY, "rb").read()
        open(os.path.join(module_dir, "banks", "MicroKorgFactory.syx"), "wb").write(
            with_names(dump, {i: f"Name {i:03d}" for i in range(128)}))
        open(os.path.join(module_dir, "banks", "Odd 'Name' & Co.syx"), "wb").write(dump)

        def get(key):
            buf = ctypes.create_string_buffer(65536)
            n = lib.tinyk_v2_get(key.encode(), buf, len(buf))
            return buf.value.decode() if n >= 0 else None

        def put(key, val):
            lib.tinyk_v2_set(key.encode(), str(val).encode())

        check(lib.tinyk_v2_create(module_dir.encode()) == 1, "instance created")
        try:
            cp = json.loads(get("chain_params"))
            meta = {e["key"]: e for e in cp}
            ok = True
        except (TypeError, ValueError) as exc:
            cp, meta, ok = [], {}, False
            print("        chain_params:", exc)
        check(ok and len(cp) >= 30, f"chain_params is valid JSON ({len(cp)} params)")
        check(meta.get("bank_file", {}).get("options") == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"],
              f"Bank options are the file names (with JSON escaping): {meta.get('bank_file', {}).get('options')}")
        check(meta.get("category", {}).get("options", [None])[0] == "Trance" and len(meta.get("patch", {}).get("options", [])) == 16,
              "Category has 8 named options, Program 16 (A1..B8)")
        items = json.loads(get("bank_list") or "[]")
        check([i["label"] for i in items] == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"] and [i["index"] for i in items] == [0, 1, 2],
              f"Banks page items: {items}")
        hier = json.loads(get("ui_hierarchy"))
        manifest = json.load(open(os.path.join(cal.ROOT, "src", "module.json"), encoding="utf-8"))
        check(hier == manifest["capabilities"]["ui_hierarchy"], "engine ui_hierarchy == module.json ui_hierarchy")
        root_knobs = hier["levels"]["root"]["knobs"]
        check(root_knobs[:2] == ["category", "patch"] and not {"bank_side", "program", "bank_file"} & set(root_knobs),
              f"main page knobs start Category, Program; no A/B or Bank knob there: {root_knobs[:4]}")

        put("bank_file", "1")
        put("category", "Retro")      # by name
        put("patch", "11")            # by index: B4
        check(get("preset") == str(64 + 5 * 8 + 3) and get("category") == "5" and get("patch") == "11",
              f"Category Retro + Program B4 -> preset {get('preset')} (expected {64 + 5 * 8 + 3})")
        check(get("preset_name") == "B.64 Name 107", f"name from the selected bank: {get('preset_name')!r}")
        put("patch", "A1")
        check(get("preset") == str(5 * 8), f"Program A1 by name -> preset {get('preset')}")
        put("preset", "1")
        check(get("preset") == "1", f"preset browser index '1' -> preset {get('preset')} (was 127 before the fix)")
        put("preset", "127")
        check(get("preset") == "127" and get("category") == "7" and get("patch") == "15",
              "preset 127 -> Category Vocoder, Program B8")
        put("bank_file", "MicroKorgFactory")
        check(get("bank_file") == "1" and get("bank_file_name") == "MicroKorgFactory", "bank by name")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    if not os.path.exists(FACTORY):
        sys.exit(f"missing {FACTORY}")
    dump = open(FACTORY, "rb").read()
    tmp = tempfile.mkdtemp(prefix="tinyk_banks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        fptr = ctypes.POINTER(ctypes.c_float)
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_select.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]

        banks = os.path.join(tmp, "banks")
        os.makedirs(banks)
        open(os.path.join(banks, "zeta.syx"), "wb").write(dump)                                # bank 3
        open(os.path.join(banks, "Alpha.syx"), "wb").write(dump)                               # bank 1
        open(os.path.join(banks, "named.SYX"), "wb").write(with_names(dump, {0: "A.11 Trancey", 1: "AcidSaw", 64: "  Spaced  "}))  # bank 2
        open(os.path.join(banks, "junk.syx"), "wb").write(b"\xF0\x42\x30\x58\x50" + b"\x00" * 100 + b"\xF7")  # too short
        single = os.path.join(cal.REF_DIR, "mk_a11.syx")
        if os.path.exists(single):
            shutil.copy(single, os.path.join(banks, "single_program.syx"))                      # program dump, not a bank
        open(os.path.join(banks, "readme.txt"), "w").write("not a bank")
        program_msg = open(single, "rb").read() if os.path.exists(single) else b"\xF0\x42\x30\x58\x40\x00\xF7"
        open(os.path.join(banks, "multi.syx"), "wb").write(program_msg + dump)                     # bank after another message
        open(os.path.join(banks, "truncated.syx"), "wb").write(dump[:20000] + b"\xF7")             # cut short
        open(os.path.join(banks, "big.syx"), "wb").write(bytes(np.random.default_rng(1).integers(0, 256, 70000, dtype=np.uint8)))
        open(os.path.join(banks, "empty.syx"), "wb").write(b"")

        print("Scanning:")
        n = lib.tinyk_bank_scan(banks.encode())
        names = [lib.tinyk_bank_name(b).decode() for b in range(1, lib.tinyk_bank_count() + 1)]
        check(n == 4 and names == ["Alpha", "multi", "named", "zeta"],
              f"4 banks loaded in alphabetical order; single-program, truncated, random, empty, .txt skipped: {names}")

        def preset(b, idx):
            t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            fx = np.zeros(len(FX_FIELDS), np.float32)
            label = ctypes.create_string_buffer(32)
            vm = lib.tinyk_bank_preset(b, idx, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), label, 32)
            return vm, np.concatenate([t1, t2, fx]), label.value.decode()

        print("Parity with presets.h (built-in bank):")
        worst, mode_ok = 0.0, True
        for idx in range(128):
            vm0, v0, _ = preset(0, idx)
            vm1, v1, _ = preset(1, idx)
            worst = max(worst, float(np.abs(v0 - v1).max()))
            mode_ok &= vm0 == vm1
        check(worst <= 1e-6 and mode_ok, f"all 128 presets match (largest difference {worst:.1e}, voice modes equal: {mode_ok})")

        print("Names:")
        check(preset(1, 0)[2] == "A.11" and preset(1, 127)[2] == "B.88", f"unnamed dump labels by code: {preset(1, 0)[2]!r}, {preset(1, 127)[2]!r}")
        labels = [preset(3, i)[2] for i in (0, 1, 2, 64)]
        check(labels == ["A.11 Trancey", "A.12 AcidSaw", "A.13", "B.11 Spaced"], f"stored names used: {labels}")

        print("Selection through the parameter API:")
        buf = ctypes.create_string_buffer(16)
        lib.tinyk_render.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_double, ctypes.c_double, fptr, ctypes.c_int]
        out = np.zeros(2 * 2000, np.float32)
        lib.tinyk_render(0, 60, 0.01, 0.02, out.ctypes.data_as(fptr), 2000)  # initialises the test instance

        def sel(key, val):
            lib.tinyk_select(key.encode(), val.encode(), buf, 16)
            return int(buf.value)
        check(sel("bank_side", "0") == 0 and sel("program", "27") == 14, "A.27 -> preset 14")
        check(sel("program", "29") == 16, "stepping 28 -> 29 snaps to 31 (preset 16)")
        check(sel("program", "30") == 15, "stepping 31 -> 30 snaps to 28 (preset 15)")
        check(sel("bank_side", "1") == 79, "switching to bank B keeps the program: B.28 -> preset 79")
        check(sel("program", "88") == 127 and sel("program", "99") == 127, "B.88 -> 127, out of range clamps")
        check(sel("bank_file", "3") == 127, "bank_file switch keeps the current program")
        check(sel("bank_file", "9") == 127, "bank_file beyond the loaded banks clamps")
        user_banks(fptr)
        host_api()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"\n{'ALL PASSED' if not FAILS else f'{len(FAILS)} FAILED'}")
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
