#!/usr/bin/env python3
"""
Checks the engine's runtime .syx bank loader (src/dsp/syx_bank.h) and the Bank / A-B / Program controls.

    python tools/test_bank_loader.py        (needs tools/FactoryBackUpDoResetAfter.syx; exit code 0 = all pass)

1. Parity: the factory dump decoded by the C loader equals the built-in presets.h bank in every float
   (presets.h is generated by tools/extracts_presets.py from the same dump; this pins the C port to it).
2. Scanning: *.syx files are loaded in case-insensitive alphabetical order; single-program dumps and junk
   are skipped; other extensions are ignored.
3. Names: a dump with stored 12-character names shows them ("A.11 Trancey" style names are kept as is,
   plain names get the code prepended); a dump without names labels presets by code ("A.11").
4. Selection: bank_file / bank_side / program select the right preset through the parameter API.
6. Host API: through the same v2 entry points the Schwung host calls (create with a module folder,
   set/get strings): live chain_params (Bank options = file names, Category, Program), the Banks page
   item list, Category/Program/preset selection and names, and ui_hierarchy identical to module.json.
5. Your banks: every .syx in the repo's banks/ folder is scanned as the module would; each loaded bank is
   cross-checked program by program against tools/extracts_presets.py, and skipped files are listed.
"""
import contextlib
import io
import json
import ctypes
import os
import shutil
import sys
import tempfile

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import calibrate_dsp as cal  # noqa: E402
from extracts_presets import ARP_FIELDS, FX_FIELDS, TIMBRE_FIELDS, load_programs, parse_program, unpack_7to8  # noqa: E402

FACTORY = os.path.join(os.path.dirname(HERE), "banks", "TinyK_Default.syx")  # the source of presets.h (tools/make_default_bank.py)
USER_BANKS = os.path.join(cal.ROOT, "banks")
FAILS = []


def check(cond, what):
    print(("  PASS  " if cond else "  FAIL  ") + what)
    if not cond:
        FAILS.append(what)


def pack_7to8(raw):
    """Inverse of unpack_7to8: 7 data bytes -> [MSB bits][7 bytes with bit 7 cleared]."""
    out = bytearray()
    for i in range(0, len(raw), 7):
        chunk = raw[i:i + 7]
        out.append(sum(1 << j for j, b in enumerate(chunk) if b & 0x80))
        out.extend(b & 0x7F for b in chunk)
    return bytes(out)


def with_names(dump, names):
    """The factory dump with program names written into bytes 0..11 of the given programs."""
    start, end = dump.find(b"\xF0"), dump.rfind(b"\xF7")
    raw = bytearray(unpack_7to8(dump[start + 5:end]))
    for idx, name in names.items():
        raw[idx * 254: idx * 254 + 12] = name.ljust(12)[:12].encode("ascii")
    return dump[:start + 5] + pack_7to8(raw) + b"\xF7"


def user_banks(fptr):
    """Scan the repo's banks/ folder with a separate engine copy, as the module would at start-up."""
    files = sorted((f for f in os.listdir(USER_BANKS) if f.lower().endswith(".syx")), key=str.lower) if os.path.isdir(USER_BANKS) else []
    print(f"\nYour banks ({USER_BANKS}, {len(files)} .syx files):")
    if not files:
        print("  (none)")
        return
    tmp = tempfile.mkdtemp(prefix="tinyk_userbanks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))  # fresh library: its bank table starts empty
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_bank_arp.argtypes = [ctypes.c_int, ctypes.c_int, fptr]
        n = lib.tinyk_bank_scan(USER_BANKS.encode())
        loaded = [lib.tinyk_bank_name(b).decode() for b in range(1, n + 1)]
        skipped = [f for f in files if os.path.splitext(f)[0] not in loaded]
        for b, name in enumerate(loaded, 1):
            with contextlib.redirect_stdout(io.StringIO()):
                ref = [parse_program(i, prog) for i, prog in enumerate(load_programs(os.path.join(USER_BANKS, name + ".syx")))]
            worst, labels, named, vocoders = 0.0, [], 0, 0
            for i in range(128):
                t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                fx = np.zeros(len(FX_FIELDS), np.float32)
                lab = ctypes.create_string_buffer(32)
                vm = lib.tinyk_bank_preset(b, i, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), lab, 32)
                want = np.array([ref[i]["t1"][f] for f in TIMBRE_FIELDS] + [ref[i]["t2"][f] for f in TIMBRE_FIELDS]
                                + [ref[i]["fx"][f] for f in FX_FIELDS], np.float32)
                worst = max(worst, float(np.abs(np.concatenate([t1, t2, fx]) - want).max()))
                arp = np.zeros(len(ARP_FIELDS), np.float32)
                n_arp = lib.tinyk_bank_arp(b, i, arp.ctypes.data_as(fptr))
                want_arp = np.array([ref[i]["arp"][f] for f in ARP_FIELDS], np.float32)
                worst = max(worst, float(np.abs(arp - want_arp).max()) if n_arp == len(ARP_FIELDS) else 1.0)
                worst = max(worst, 0.0 if vm == int(ref[i]["voice_mode"]) else 1.0)
                labels.append(lab.value.decode())
                named += len(labels[-1]) > 4
                vocoders += not ref[i]["data_valid"]
            check(worst <= 1e-6, f"bank {b} {name!r}: 128 programs, {named} named, {vocoders} vocoder; "
                                 f"matches extracts_presets.py (max diff {worst:.1e}); e.g. {labels[0]!r}, {labels[1]!r}, {labels[64]!r}")
        for f in skipped:
            print(f"  skip  {f} ({os.path.getsize(os.path.join(USER_BANKS, f))} bytes: not a 128-program bank dump)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def host_api():
    """The module as the host drives it: v2_create_instance(module_dir) scans <module_dir>/banks."""
    print("\nHost API (v2 entry points):")
    tmp = tempfile.mkdtemp(prefix="tinyk_hostapi_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_v2_create.argtypes = [ctypes.c_char_p]
        lib.tinyk_v2_set.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
        lib.tinyk_v2_get.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        module_dir = os.path.join(tmp, "module")
        os.makedirs(os.path.join(module_dir, "banks"))
        dump = open(FACTORY, "rb").read()
        open(os.path.join(module_dir, "banks", "MicroKorgFactory.syx"), "wb").write(
            with_names(dump, {i: f"Name {i:03d}" for i in range(128)}))
        open(os.path.join(module_dir, "banks", "Odd 'Name' & Co.syx"), "wb").write(dump)

        def get(key):
            buf = ctypes.create_string_buffer(65536)
            n = lib.tinyk_v2_get(key.encode(), buf, len(buf))
            return buf.value.decode() if n >= 0 else None

        def put(key, val):
            lib.tinyk_v2_set(key.encode(), str(val).encode())

        check(lib.tinyk_v2_create(module_dir.encode()) == 1, "instance created")
        try:
            cp = json.loads(get("chain_params"))
            meta = {e["key"]: e for e in cp}
            ok = True
        except (TypeError, ValueError) as exc:
            cp, meta, ok = [], {}, False
            print("        chain_params:", exc)
        check(ok and len(cp) >= 30, f"chain_params is valid JSON ({len(cp)} params)")
        check(meta.get("bank_file", {}).get("options") == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"],
              f"Bank options are the file names (with JSON escaping): {meta.get('bank_file', {}).get('options')}")
        codes = [f"{s}{c}" for s in "AB" for c in range(1, 9)]
        prog = meta.get("patch", {})
        check(meta.get("category", {}).get("options", [None])[0] == "Trance" and len(prog.get("options", [])) == 16
              and prog.get("short_options") == codes,
              "Category has 8 named options, Program 16 (short_options A1..B8)")
        check(prog.get("options") == [get(f"preset_name:{(i // 8) * 64 + i % 8}") for i in range(16)],
              f"Program options are the category's patch names: {prog.get('options', [])[:2]} ... {prog.get('options', [])[-1:]}")
        items = json.loads(get("bank_list") or "[]")
        check([i["label"] for i in items] == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"] and [i["index"] for i in items] == [0, 1, 2],
              f"Banks page items: {items}")
        hier = json.loads(get("ui_hierarchy"))
        manifest = json.load(open(os.path.join(cal.ROOT, "src", "module.json"), encoding="utf-8"))
        check(hier == manifest["capabilities"]["ui_hierarchy"], "engine ui_hierarchy == module.json ui_hierarchy")
        levels = hier["levels"]
        pages = {"perf": ("Perf [T1]", ["category", "patch", "cutoff", "resonance", "attack2", "release2", "arp_on", "mod_wheel"]),
                 "osc": ("Osc/Timbre [T1]", ["wave1", "pulse_width", "wave2", "osc2_semi", "osc2_tune", "voice_mode",
                                             "timbre_edit", "timbre_balance"]),
                 "env": ("Envelopes [T1]", ["attack1", "decay1", "sustain1", "release1", "decay2", "sustain2", "keytrack", "env_int"]),
                 "fx": ("Effects", ["chorus_mix", "delay_time", "delay_feedback", "delay_mix", "lfo1_rate", "lfo2_rate",
                                    "master_vol", "pan"]),
                 "mix": ("Mix/Filter [T1]", ["osc_mix", "noise_level", "sync_ring", "filter_type", "portamento", "level", "drive"]),
                 "arpset": ("Arp Settings", ["arp_type", "arp_range", "arp_resolution", "arp_gate", "arp_swing", "arp_latch",
                                             "arp_key_sync", "arp_target"]),
                 "steps": ("Arp Steps", [f"arp_step{n}" for n in range(1, 9)])}
        check([p.get("level") for p in levels["root"]["params"]] == [k for k in pages if k not in ("arpset", "steps")]
              + ["bank", "arpset", "steps"]
              and levels["root"]["knobs"] == [],
              f"root is the preset browser with the page levels in order: {[p.get('level') for p in levels['root']['params']]}")
        check(all(levels[k]["name"] == name and levels[k]["knobs"] == knobs for k, (name, knobs) in pages.items()),
              "Perf / Osc/Timbre / Envelopes / Effects / Mix/Filter / Arp Settings / Arp Steps pages hold their knobs (per-timbre pages badged [T1])")
        every = [k for _, knobs in pages.values() for k in knobs]
        check(len(every) == len(set(every)) and not {"bank_side", "program", "bank_file", "detune", "sub_level"} & set(every),
              "each control on one page; no A/B, Bank, Detune or Sub Level knob")
        check(meta["wave1"].get("options") == ["Saw", "Square", "Triangle", "Sine", "Vox", "DWGS", "Noise"]
              and meta["wave1"].get("short_options") == ["SAW", "SQR", "TRI", "SIN", "VOX", "DWG", "NZ"]
              and meta["wave2"].get("short_options") == ["SAW", "SQR", "TRI"] and "short_name" not in meta["cutoff"],
              "Wave 1/2 are enums named for the waveform; Timbre 1 labels are the plain ones")
        missing = [k for k in every if k not in meta]
        check(not missing, f"chain_params describes every page knob (missing: {missing})")

        # Wave enums travel as indices (or names); Semi / Tune split detune; Level / Noise are per-timbre extras
        put("wave1", "3")
        put("wave2", "Square")
        w = [get("wave1"), get("wave2")]
        put("wave1", "0.0")           # a normalized value from a generic control
        check(w == ["3", "1"] and get("wave1") == "0", f"wave1 index 3 -> {w[0]}, wave2 'Square' -> {w[1]}, '0.0' -> {get('wave1')}")
        put("osc2_semi", "-7")
        put("osc2_tune", "25")
        st = [get("osc2_semi"), get("osc2_tune")]
        put("osc2_semi", "40")
        check(st == ["-7", "25"] and get("osc2_semi") == "24" and get("osc2_tune") == "0",
              f"Semi -7 / Tune +25 read back {st}; Semi clamps to {get('osc2_semi')} (the +-24 st range, so no tune above it)")
        put("level", "0.25")
        put("noise_level", "0.5")
        check(get("level") == "0.2500" and get("noise_level") == "0.5000", f"Level / Noise: {get('level')}, {get('noise_level')}")
        mw0 = get("mod_wheel")
        put("mod_wheel", "100")
        check(mw0 == "0" and get("mod_wheel") == "100" and meta["mod_wheel"].get("max") == 127
              and meta["mod_wheel"].get("short_name") == "MOD",
              f"Mod Wheel knob (MOD, 0..127): starts {mw0}, set 100 -> {get('mod_wheel')}")
        put("mod_wheel", "0")

        # Timbre 2 in Layer mode: the per-timbre page names and labels say T2, global ones stay plain
        check(get("is_loading") == "0", "no label change pending")
        put("voice_mode", "1")
        put("timbre_edit", "1")
        loading = [get("is_loading"), get("is_loading")]
        hier2 = json.loads(get("ui_hierarchy"))
        meta2 = {e["key"]: e for e in json.loads(get("chain_params"))}
        check(loading == ["1", "0"] and hier2["levels"]["perf"]["name"] == "Perf [T2]" and hier2["levels"]["fx"]["name"] == "Effects"
              and meta2["cutoff"].get("short_name") == "T2.CUT" and meta2["cutoff"].get("label") == "T2 Cutoff"
              and meta2["attack2"].get("short_name") == "T2.ATK" and "short_name" not in meta2["delay_mix"]
              and "short_name" not in meta2["patch"],
              f"Timbre 2 edit: is_loading {loading}, page {hier2['levels']['perf']['name']!r}, "
              f"cutoff cell {meta2['cutoff'].get('short_name')!r}")
        put("level", "0.75")
        put("timbre_edit", "0")
        check(get("level") == "0.2500", f"Level edits the selected timbre only (Timbre 1 kept {get('level')})")
        put("voice_mode", "0")
        get("is_loading")             # the host takes the change back to Timbre 1
        # Filter Type and Sync / Ring are option boxes; Sync / Ring in the hardware's order (off, ring, sync,
        # ring sync), which the engine remaps to its own (off, sync, ring, both)
        check(meta["filter_type"].get("short_options") == ["LPF24", "LPF12", "BPF12", "HPF12"]
              and meta["sync_ring"].get("short_options") == ["OFF", "RING", "SYNC", "R.SNC"]
              and meta["voice_mode"].get("short_options") == ["SNGL", "LAYR"]
              and meta["timbre_edit"].get("short_options") == ["T1", "T2"],
              "Filter Type / Sync-Ring / Voice Mode / Timbre Edit option-box texts")
        put("filter_type", "BPF12")
        ft = get("filter_type")
        put("sync_ring", "R.SNC")
        sr = [get("sync_ring")]
        put("sync_ring", "1")
        sr.append(get("sync_ring"))
        check(ft == "2" and sr == ["3", "1"], f"by name / index: BPF12 -> {ft}, R.SNC -> {sr[0]}, Ring (1) -> {sr[1]}")
        put("bank_file", "1")
        seen = {}
        for idx in (9, 2, 23, 0, 17):   # factory programs with hardware ring, sync, ring sync; BPF12, HPF12
            put("preset", str(idx))
            seen[idx] = (get("sync_ring"), get("filter_type"))
        check([seen[i][0] for i in (9, 2, 23)] == ["1", "2", "3"] and seen[0][1] == "2" and seen[17][1] == "3",
              f"decoded programs report the hardware's mode: {seen}")
        put("bank_file", "0")
        get("is_loading")             # the host takes the bank / category change

        # Program labels follow Category and Bank; is_loading answers "1" once per unreported change so the
        # host re-reads chain_params on the 1 -> 0 edge
        loading0 = get("is_loading")
        put("bank_file", "1")
        put("category", "Retro")      # by name
        loading = [get("is_loading"), get("is_loading")]
        check(loading0 == "0" and loading == ["1", "0"], f"is_loading after Bank/Category change: {loading0} then {loading}")
        prog = {e["key"]: e for e in json.loads(get("chain_params"))}["patch"]
        check(prog["options"][11] == "B.64 Name 107" and get("is_loading") == "0",
              f"re-read Program options name the new category and bank: {prog['options'][11]!r}")
        put("patch", "11")            # by index: B4
        check(get("preset") == str(64 + 5 * 8 + 3) and get("category") == "5" and get("patch") == "11"
              and get("is_loading") == "0",
              f"Category Retro + Program B4 -> preset {get('preset')} (expected {64 + 5 * 8 + 3}); no label change")
        check(get("preset_name") == "B.64 Name 107", f"name from the selected bank: {get('preset_name')!r}")
        put("patch", "A.62 Name 041")
        check(get("preset") == str(5 * 8 + 1), f"Program by its label -> preset {get('preset')}")
        put("patch", "A1")
        check(get("preset") == str(5 * 8), f"Program A1 by name -> preset {get('preset')}")
        put("preset", "1")
        check(get("preset") == "1", f"preset browser index '1' -> preset {get('preset')} (was 127 before the fix)")
        put("preset", "127")
        check(get("preset") == "127" and get("category") == "7" and get("patch") == "15",
              "preset 127 -> Category Vocoder, Program B8")
        put("bank_file", "MicroKorgFactory")
        check(get("bank_file") == "1" and get("bank_file_name") == "MicroKorgFactory", "bank by name")

        # Slot state (the host's autosave / boot restore): edits survive a round trip through another program
        put("preset", "20")
        put("voice_mode", "1")
        put("timbre_edit", "1")
        put("cutoff", "0.123")
        put("level", "0.3")
        put("timbre_edit", "0")
        put("resonance", "0.777")
        put("delay_mix", "0.42")
        before = {k: get(k) for k in ("bank_file_name", "preset", "voice_mode", "resonance", "delay_mix", "level")}
        state = get("state")
        try:
            doc = json.loads(state)
        except ValueError:
            doc = {}
        check(doc.get("tinyk_state") == 1 and doc.get("bank") == "MicroKorgFactory" and doc.get("preset") == 20
              and len(doc.get("params", [])) == 35 and len(doc.get("extra2", [])) == 30,
              f"state is JSON ({len(state)} bytes): bank, preset, params, extras")
        put("bank_file", "0")
        put("preset", "99")
        put("state", state)
        after = {k: get(k) for k in before}
        put("timbre_edit", "1")
        t2 = (get("cutoff"), get("level"))
        check(after == before and t2 == ("0.1230", "0.3000"), f"state restores bank, program and edits: {after}, T2 {t2}")
        # A state saved before Osc 1 Ctrl 1 / 2 were decoded (24 extras) still restores its extras
        old_doc = dict(doc)
        old_doc["extra2"] = doc["extra2"][:24]
        old_doc["extra2"][2] = 0.4  # Timbre 2 level
        put("preset", "99")
        put("state", json.dumps(old_doc))
        put("timbre_edit", "1")
        check(get("level") == "0.4000" and get("preset") == "20", f"24-value extras (older state) restore: level {get('level')}")
        put("preset", "5")
        put("state", "{\"tinyk_state\":1,\"preset\":7,\"params\":[1,2]}")
        check(get("preset") == "7" and get("bank_file_name") == "Built-in", "a partial state keeps the program's values")
        put("state", "garbage")
        check(get("preset") == "7", "a state that is not TinyK's is ignored")

        # The Arp knob: a program loads its stored arp setting; the knob overrides it; the slot state keeps it
        put("bank_file", "0")
        put("preset", "8")  # A.21: arp on
        a21_on = get("arp_on")
        put("preset", "2")  # A.13: arp off
        a13_on = get("arp_on")
        put("arp_on", "On")
        knob_on = get("arp_on")
        st = json.loads(get("state"))
        put("preset", "2")
        reloaded = get("arp_on")
        put("state", json.dumps(st))
        check(a21_on == "1" and a13_on == "0" and knob_on == "1" and st.get("arp_on") == 1 and reloaded == "0"
              and get("arp_on") == "1",
              f"Arp: programs load their own (A.21 {a21_on}, A.13 {a13_on}); knob On -> {knob_on}; saved in the state and restored")
        meta_arp = {p["key"]: p for p in json.loads(get("chain_params"))}.get("arp_on", {})
        check(meta_arp.get("options") == ["Off", "On"] and "arp_on" in manifest["capabilities"]["ui_hierarchy"]["levels"]["perf"]["knobs"],
              "Arp knob on the Perf page, an Off / On enum in chain_params")
        put("arp_on", "0")

        # Arp Steps: 1 = play, 0 = rest; starts from the program's stored pattern, edits are live and saved
        put("preset", "8")  # A.21: pattern 0x52 (steps 2, 5, 7 rest), 8 steps
        stored = [get(f"arp_step{n}") for n in range(1, 9)]
        put("arp_step1", "Rest")
        put("arp_step2", "1")
        edited = [get(f"arp_step{n}") for n in range(1, 9)]
        st = json.loads(get("state"))
        put("preset", "8")
        reloaded = [get(f"arp_step{n}") for n in range(1, 9)]
        put("state", json.dumps(st))
        restored = [get(f"arp_step{n}") for n in range(1, 9)]
        meta_st = {p["key"]: p for p in json.loads(get("chain_params"))}.get("arp_step3", {})
        check(stored == list("10110101") and edited == list("01110101") and st.get("arp_pattern") == 0x51
              and reloaded == stored and restored == edited and meta_st.get("options") == ["Rest", "Play"],
              f"Arp Steps: A.21 loads {''.join(stored)}; Step 1 Rest / Step 2 Play -> {''.join(edited)} (pattern "
              f"0x{st.get('arp_pattern', 0):02X} in the state); a program reload restores the stored steps, the state the edit")
        st1 = dict(json.loads(get("state")), arp_length=1, arp_pattern=0)  # an MS2000-style 1-step pattern
        put("state", json.dumps(st1))
        st64 = json.loads(get("state"))
        put("arp_step4", "Rest")
        st64b = json.loads(get("state"))
        check(st64.get("arp_length") == 1 and st64b.get("arp_length") == 4 and get("arp_step4") == "0"
              and get("arp_step2") == "1" and get("arp_step3") == "1",
              f"Step 4 past a {st64.get('arp_length')}-step pattern extends it to {st64b.get('arp_length')} steps, steps between play")
        # Arp Settings: A.21's stored values, set by option name or index, saved and restored
        put("preset", "8")
        keys8 = ["arp_type", "arp_range", "arp_resolution", "arp_gate", "arp_swing", "arp_latch", "arp_key_sync", "arp_target"]
        a21 = [get(k) for k in keys8]
        for k, v in zip(keys8, ["ALT1", "3", "1/8", "55", "-40", "Off", "0", "Timbre 2"]):
            put(k, v)
        edited8 = [get(k) for k in keys8]
        st8 = json.loads(get("state"))
        put("preset", "8")
        back8 = [get(k) for k in keys8]
        put("state", json.dumps(st8))
        restored8 = [get(k) for k in keys8]
        meta8 = {p["key"]: p for p in json.loads(get("chain_params"))}
        check(a21 == ["0", "1", "1", "80", "0", "1", "1", "1"] and edited8 == ["2", "3", "3", "55", "-40", "0", "0", "2"]
              and back8 == a21 and restored8 == edited8 and st8.get("arp_type") == 2 and st8.get("arp_swing") == -40
              and meta8.get("arp_type", {}).get("options") == ["UP", "DOWN", "ALT1", "ALT2", "RANDOM", "TRIGGER"]
              and meta8.get("arp_swing", {}).get("min") == -100 and meta8.get("arp_target", {}).get("short_options") == ["BOTH", "T1", "T2"],
              f"Arp Settings: A.21 {a21} -> set by name {edited8}, saved in the state; the program restores its own, the state the edits")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    if not os.path.exists(FACTORY):
        sys.exit(f"missing {FACTORY}")
    dump = open(FACTORY, "rb").read()
    dump = with_names(dump, {i: "" for i in range(128)})  # the scan / label checks start from an unnamed bank
    tmp = tempfile.mkdtemp(prefix="tinyk_banks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        fptr = ctypes.POINTER(ctypes.c_float)
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_select.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]

        banks = os.path.join(tmp, "banks")
        os.makedirs(banks)
        open(os.path.join(banks, "zeta.syx"), "wb").write(dump)                                # bank 3
        open(os.path.join(banks, "Alpha.syx"), "wb").write(dump)                               # bank 1
        open(os.path.join(banks, "named.SYX"), "wb").write(with_names(dump, {0: "A.11 Trancey", 1: "AcidSaw", 64: "  Spaced  "}))  # bank 2
        open(os.path.join(banks, "junk.syx"), "wb").write(b"\xF0\x42\x30\x58\x50" + b"\x00" * 100 + b"\xF7")  # too short
        single = os.path.join(cal.REF_DIR, "mk_a11.syx")
        if os.path.exists(single):
            shutil.copy(single, os.path.join(banks, "single_program.syx"))                      # program dump, not a bank
        open(os.path.join(banks, "readme.txt"), "w").write("not a bank")
        program_msg = open(single, "rb").read() if os.path.exists(single) else b"\xF0\x42\x30\x58\x40\x00\xF7"
        open(os.path.join(banks, "multi.syx"), "wb").write(program_msg + dump)                     # bank after another message
        open(os.path.join(banks, "truncated.syx"), "wb").write(dump[:20000] + b"\xF7")             # cut short
        open(os.path.join(banks, "big.syx"), "wb").write(bytes(np.random.default_rng(1).integers(0, 256, 70000, dtype=np.uint8)))
        open(os.path.join(banks, "empty.syx"), "wb").write(b"")

        print("Scanning:")
        n = lib.tinyk_bank_scan(banks.encode())
        names = [lib.tinyk_bank_name(b).decode() for b in range(1, lib.tinyk_bank_count() + 1)]
        check(n == 4 and names == ["Alpha", "multi", "named", "zeta"],
              f"4 banks loaded in alphabetical order; single-program, truncated, random, empty, .txt skipped: {names}")

        def preset(b, idx):
            t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            fx = np.zeros(len(FX_FIELDS), np.float32)
            label = ctypes.create_string_buffer(32)
            vm = lib.tinyk_bank_preset(b, idx, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), label, 32)
            return vm, np.concatenate([t1, t2, fx]), label.value.decode()

        print("Parity with presets.h (built-in bank):")
        worst, mode_ok = 0.0, True
        for idx in range(128):
            vm0, v0, _ = preset(0, idx)
            vm1, v1, _ = preset(1, idx)
            worst = max(worst, float(np.abs(v0 - v1).max()))
            mode_ok &= vm0 == vm1
        check(worst <= 1e-6 and mode_ok, f"all 128 presets match (largest difference {worst:.1e}, voice modes equal: {mode_ok})")

        print("Names:")
        check(preset(1, 0)[2] == "A.11" and preset(1, 127)[2] == "B.88", f"unnamed dump labels by code: {preset(1, 0)[2]!r}, {preset(1, 127)[2]!r}")
        labels = [preset(3, i)[2] for i in (0, 1, 2, 64)]
        check(labels == ["A.11 Trancey", "A.12 AcidSaw", "A.13", "B.11 Spaced"], f"stored names used: {labels}")

        print("Selection through the parameter API:")
        buf = ctypes.create_string_buffer(16)
        lib.tinyk_render.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_double, ctypes.c_double, fptr, ctypes.c_int]
        out = np.zeros(2 * 2000, np.float32)
        lib.tinyk_render(0, 60, 0.01, 0.02, out.ctypes.data_as(fptr), 2000)  # initialises the test instance

        def sel(key, val):
            lib.tinyk_select(key.encode(), val.encode(), buf, 16)
            return int(buf.value)
        check(sel("bank_side", "0") == 0 and sel("program", "27") == 14, "A.27 -> preset 14")
        check(sel("program", "29") == 16, "stepping 28 -> 29 snaps to 31 (preset 16)")
        check(sel("program", "30") == 15, "stepping 31 -> 30 snaps to 28 (preset 15)")
        check(sel("bank_side", "1") == 79, "switching to bank B keeps the program: B.28 -> preset 79")
        check(sel("program", "88") == 127 and sel("program", "99") == 127, "B.88 -> 127, out of range clamps")
        check(sel("bank_file", "3") == 127, "bank_file switch keeps the current program")
        check(sel("bank_file", "9") == 127, "bank_file beyond the loaded banks clamps")
        user_banks(fptr)
        host_api()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"\n{'ALL PASSED' if not FAILS else f'{len(FAILS)} FAILED'}")
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
