#!/usr/bin/env python3
"""
Checks the engine's runtime .syx bank loader (src/dsp/syx_bank.h) and the Bank / A-B / Program controls.

    python tools/test_bank_loader.py        (needs tools/FactoryBackUpDoResetAfter.syx; exit code 0 = all pass)

1. Parity: the factory dump decoded by the C loader equals the built-in presets.h bank in every float
   (presets.h is generated by tools/extracts_presets.py from the same dump; this pins the C port to it).
2. Scanning: *.syx files are loaded in case-insensitive alphabetical order; single-program dumps and junk
   are skipped; other extensions are ignored.
3. Names: a dump with stored 12-character names shows them ("A.11 Trancey" style names are kept as is,
   plain names get the code prepended); a dump without names labels presets by code ("A.11").
4. Selection: bank_file / bank_side / program select the right preset through the parameter API.
6. Host API: through the same v2 entry points the Schwung host calls (create with a module folder,
   set/get strings): live chain_params (Bank options = file names, Category, Program), the Banks page
   item list, Category/Program/preset selection and names, and ui_hierarchy identical to module.json.
5. Your banks: every .syx in the repo's banks/ folder is scanned as the module would; each loaded bank is
   cross-checked program by program against tools/extracts_presets.py, and skipped files are listed.
"""
import contextlib
import io
import json
import ctypes
import os
import shutil
import sys
import tempfile

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import calibrate_dsp as cal  # noqa: E402
from extracts_presets import ARP_FIELDS, FX_FIELDS, TIMBRE_FIELDS, load_programs, parse_program, unpack_7to8  # noqa: E402

FACTORY = os.path.join(os.path.dirname(HERE), "banks", "TinyK_Default.syx")  # the source of presets.h (tools/make_default_bank.py)
USER_BANKS = os.path.join(cal.ROOT, "banks")
FAILS = []


def check(cond, what):
    print(("  PASS  " if cond else "  FAIL  ") + what)
    if not cond:
        FAILS.append(what)


def pack_7to8(raw):
    """Inverse of unpack_7to8: 7 data bytes -> [MSB bits][7 bytes with bit 7 cleared]."""
    out = bytearray()
    for i in range(0, len(raw), 7):
        chunk = raw[i:i + 7]
        out.append(sum(1 << j for j, b in enumerate(chunk) if b & 0x80))
        out.extend(b & 0x7F for b in chunk)
    return bytes(out)


def with_names(dump, names):
    """The factory dump with program names written into bytes 0..11 of the given programs."""
    start, end = dump.find(b"\xF0"), dump.rfind(b"\xF7")
    raw = bytearray(unpack_7to8(dump[start + 5:end]))
    for idx, name in names.items():
        raw[idx * 254: idx * 254 + 12] = name.ljust(12)[:12].encode("ascii")
    return dump[:start + 5] + pack_7to8(raw) + b"\xF7"


def user_banks(fptr):
    """Scan the repo's banks/ folder with a separate engine copy, as the module would at start-up."""
    files = sorted((f for f in os.listdir(USER_BANKS) if f.lower().endswith(".syx")), key=str.lower) if os.path.isdir(USER_BANKS) else []
    print(f"\nYour banks ({USER_BANKS}, {len(files)} .syx files):")
    if not files:
        print("  (none)")
        return
    tmp = tempfile.mkdtemp(prefix="tinyk_userbanks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))  # fresh library: its bank table starts empty
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_bank_arp.argtypes = [ctypes.c_int, ctypes.c_int, fptr]
        n = lib.tinyk_bank_scan(USER_BANKS.encode())
        loaded = [lib.tinyk_bank_name(b).decode() for b in range(1, n + 1)]
        skipped = [f for f in files if os.path.splitext(f)[0] not in loaded]
        for b, name in enumerate(loaded, 1):
            with contextlib.redirect_stdout(io.StringIO()):
                ref = [parse_program(i, prog) for i, prog in enumerate(load_programs(os.path.join(USER_BANKS, name + ".syx")))]
            worst, labels, named, vocoders = 0.0, [], 0, 0
            for i in range(128):
                t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
                fx = np.zeros(len(FX_FIELDS), np.float32)
                lab = ctypes.create_string_buffer(32)
                vm = lib.tinyk_bank_preset(b, i, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), lab, 32)
                want = np.array([ref[i]["t1"][f] for f in TIMBRE_FIELDS] + [ref[i]["t2"][f] for f in TIMBRE_FIELDS]
                                + [ref[i]["fx"][f] for f in FX_FIELDS], np.float32)
                worst = max(worst, float(np.abs(np.concatenate([t1, t2, fx]) - want).max()))
                arp = np.zeros(len(ARP_FIELDS), np.float32)
                n_arp = lib.tinyk_bank_arp(b, i, arp.ctypes.data_as(fptr))
                want_arp = np.array([ref[i]["arp"][f] for f in ARP_FIELDS], np.float32)
                worst = max(worst, float(np.abs(arp - want_arp).max()) if n_arp == len(ARP_FIELDS) else 1.0)
                worst = max(worst, 0.0 if vm == (2 if not ref[i]["data_valid"] else int(ref[i]["voice_mode"])) else 1.0)  # 2 = vocoder
                labels.append(lab.value.decode())
                named += len(labels[-1]) > 4
                vocoders += not ref[i]["data_valid"]
            check(worst <= 1e-6, f"bank {b} {name!r}: 128 programs, {named} named, {vocoders} vocoder; "
                                 f"matches extracts_presets.py (max diff {worst:.1e}); e.g. {labels[0]!r}, {labels[1]!r}, {labels[64]!r}")
        for f in skipped:
            print(f"  skip  {f} ({os.path.getsize(os.path.join(USER_BANKS, f))} bytes: not a 128-program bank dump)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def with_modes(dump, modes):
    """The factory dump with the voice mode (byte 16 bits 4-5: 0 Single, 2 Layer, 3 Vocoder) set on the given programs."""
    start, end = dump.find(b"\xF0"), dump.rfind(b"\xF7")
    raw = bytearray(unpack_7to8(dump[start + 5:end]))
    for idx, mode in modes.items():
        raw[idx * 254 + 16] = (raw[idx * 254 + 16] & ~0x30) | (mode << 4)
    return dump[:start + 5] + pack_7to8(raw) + b"\xF7"


def vocoder_banks():
    """Vocoder programs (voice mode byte = 3) are left out of what an instance offers, wherever they sit in the bank."""
    print("\nVocoder programs are filtered out (any bank):")
    tmp = tempfile.mkdtemp(prefix="tinyk_vocoder_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_v2_create.argtypes = [ctypes.c_char_p]
        lib.tinyk_v2_set.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
        lib.tinyk_v2_get.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        module_dir = os.path.join(tmp, "module")
        os.makedirs(os.path.join(module_dir, "banks"))
        dump = open(FACTORY, "rb").read()
        progs = load_programs(FACTORY)
        voc = [i for i, p in enumerate(progs) if ((p[16] >> 4) & 3) == 3]
        row8 = [r for r in range(128) if r % 64 >= 56]
        extra = 3  # A.14, a synth program, flagged as vocoder as well: no longer the factory layout
        banks = {
            "A_default": dump,                                                  # TinyK_Default.syx: 16 vocoder, row 8
            "B_novoc": with_modes(dump, {i: 0 for i in voc}),                    # a bank without any
            "C_scattered": with_modes(dump, {extra: 3}),                         # 17, one outside row 8
            "D_allvoc": with_modes(dump, {i: 3 for i in range(128)}),            # nothing but vocoder
            "E_names": with_names(with_modes(dump, {extra: 3}), {i: f"Name {i:03d}" for i in range(128)}),
            "F_row8a": with_modes(dump, {i: 0 for i in range(120, 128)}),         # row 8 vocoder on the A side only
            "G_gap": with_modes(dump, {i: 3 for i in list(range(16, 24)) + list(range(80, 88))}),  # row 3 vocoder as well
        }
        for name, d in banks.items():
            open(os.path.join(module_dir, "banks", name + ".syx"), "wb").write(d)

        def get(key):
            buf = ctypes.create_string_buffer(65536)
            n = lib.tinyk_v2_get(key.encode(), buf, len(buf))
            return buf.value.decode() if n >= 0 else None

        def put(key, val):
            lib.tinyk_v2_set(key.encode(), str(val).encode())

        def meta():
            return {e["key"]: e for e in json.loads(get("chain_params"))}

        check(lib.tinyk_v2_create(module_dir.encode()) == 1, "instance created")
        check(voc == row8 and len(voc) == 16, f"TinyK_Default.syx flags exactly the 16 row-8 programs as vocoder: {voc}")

        # Built-in bank (presets.h): 112 programs, seven categories, the matrix without its vocoder row
        m = meta()
        names = [get(f"preset_name:{i}") for i in range(112)]
        check(get("preset_count") == "112" and get("preset_name:112") is None and get("category_count") == "7",
              f"Built-in: preset_count {get('preset_count')}, category_count {get('category_count')}, preset_name:112 -> {get('preset_name:112')}")
        check(m["category"]["options"] == ["Trance", "Techno/House", "Electronica", "DnB/Breaks", "Hiphop/Vintage", "Retro", "SE/Hit"],
              f"Category options without the Vocoder row: {m['category']['options']}")
        check(names[0].startswith("A.11") and names[55].startswith("A.78") and names[56].startswith("B.11")
              and names[111].startswith("B.78") and not any(n.startswith(("A.8", "B.8")) for n in names),
              f"labels run A.11-A.78 then B.11-B.78: {names[0]!r} {names[55]!r} {names[56]!r} {names[111]!r}")
        seen, bad = set(), []
        for i in range(112):
            put("preset", i)
            row = get("preset_name")
            seen.add(row)
            if get("preset") != str(i) or get("preset_name") != names[i] or int(get("category")) > 6:
                bad.append(i)
        check(not bad and len(seen) == 112, f"every one of the 112 ordinals loads its own program ({len(bad)} wrong)")
        put("preset", 500)
        check(get("preset") == "111", f"jog past the end clamps to the last program: {get('preset')}")
        put("category", 7)
        put("patch", 15)
        check(get("category") == "6" and get("preset_name").startswith("B.78"), f"Category 8 / B8 clamps to {get('preset_name')!r}")
        put("program", "88")
        check(get("category") == "6" and get("patch") == "15", f"program 88 -> {get('preset_name')!r}")
        put("preset", 111)
        put("bank_file", "A_default")
        check(get("bank_file_name") == "A_default" and get("preset_count") == "112" and get("preset") == "111",
              f"a factory-layout .syx bank: 112 programs, ordinal kept ({get('preset_count')}, {get('preset')})")

        # A bank without vocoder programs keeps all 128 and the matrix (the 8th category holds ordinary programs)
        put("bank_file", "B_novoc")
        m = meta()
        put("preset", 127)
        check(get("preset_count") == "128" and get("category_count") == "8" and m["category"]["options"][7] == "Other"
              and get("preset") == "127" and get("preset_name").startswith("B.88"),
              f"no vocoder: {get('preset_count')} programs, {get('category_count')} categories, last {get('preset_name')!r}")

        # Vocoder programs in other places: the matrix stays, each category lists the playable programs of its row
        std_names = ["Trance", "Techno/House", "Electronica", "DnB/Breaks", "Hiphop/Vintage", "Retro", "SE/Hit"]
        put("bank_file", "C_scattered")
        m = meta()
        put("preset", 110)
        check(get("preset_count") == "111" and get("category_count") == "7" and m["category"]["options"] == std_names
              and get("preset_name").startswith("B.78") and get("category") == "6" and get("patch") == "15",
              f"scattered vocoder: {get('preset_count')} programs, {get('category_count')} categories, last {get('preset_name')!r}")
        put("category", 0)
        m = meta()
        opts = m["patch"]["options"]
        check(len(opts) == 15 and opts[2].startswith("A.13") and opts[3].startswith("A.15") and opts[14].startswith("B.18")
              and m["patch"]["short_options"] == ["A1", "A2", "A3", "A5", "A6", "A7", "A8"] + [f"B{c}" for c in range(1, 9)]
              and get("patch_count") == "15",
              f"Trance lists its 15 playable programs with their own coordinates: {opts[2][:6]} {opts[3][:6]} ... {m['patch']['short_options'][:5]}")
        put("patch", 15)
        check(get("patch") == "14" and get("preset_name").startswith("B.18") and get("preset") == "62",
              f"Program past the category's last clamps to it: {get('preset_name')!r}, ordinal {get('preset')}")
        names_seen = set()
        for i in range(111):
            put("preset", i)
            names_seen.add(get("preset_name").split(" ")[0])
        check(len(names_seen) == 111 and not any(n.startswith(("A.8", "B.8", "A.14")) for n in names_seen),
              "every ordinal of the scattered bank is its own matrix program (A.14 and row 8 are not offered)")
        put("bank_file", "E_names")
        put("preset", 3)  # slot 4 (A.15): the flagged A.14 is skipped
        check(get("preset_name") == "A.15 Name 004" and get("preset_name:2") == "A.13 Name 002",
              f"matrix names stay: {get('preset_name')!r}, {get('preset_name:2')!r}")

        # Vocoder programs on the A side of row 8 only: B.81-B.88 are ordinary programs in the 8th category
        put("bank_file", "F_row8a")
        m = meta()
        put("category", 7)
        m = meta()
        check(get("preset_count") == "120" and get("category_count") == "8" and m["category"]["options"][7] == "Other"
              and get("patch_count") == "8" and m["patch"]["short_options"] == [f"B{c}" for c in range(1, 9)]
              and m["patch"]["options"][0].startswith("B.81"),
              f"half a vocoder row: {get('preset_count')} programs, category 8 'Other' with {get('patch_count')} (first {m['patch']['options'][0][:6]})")
        put("patch", 20)
        check(get("preset_name").startswith("B.88") and get("preset") == "119", f"Program past the end -> {get('preset_name')!r}")
        put("category", 99)
        check(get("category") == "7", f"Category past the end clamps: {get('category')}")

        # A whole row of vocoder programs in the middle: that category is not offered, the others keep their names
        put("bank_file", "G_gap")
        m = meta()
        check(get("preset_count") == "96" and get("category_count") == "6"
              and m["category"]["options"] == ["Trance", "Techno/House", "DnB/Breaks", "Hiphop/Vintage", "Retro", "SE/Hit"],
              f"an empty row is skipped: {get('category_count')} categories {m['category']['options']}")
        put("category", 2)
        put("patch", 0)
        check(get("preset_name").startswith("A.41"), f"third category is the matrix's 4th row: {get('preset_name')!r}")

        # A bank of nothing but vocoder programs keeps them all rather than offering nothing
        put("bank_file", "D_allvoc")
        check(get("preset_count") == "128", f"all-vocoder bank still offers {get('preset_count')} programs")

        # A saved state pointing at a vocoder slot (an old save) lands on a playable program
        put("bank_file", "A_default")
        state = json.loads(get("state"))
        state["preset"] = 125
        state["bank"] = "A_default"
        put("state", json.dumps(state))
        check(int(get("preset")) < 112, f"a state saved on a vocoder slot restores to a playable program ({get('preset')})")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def host_api():
    """The module as the host drives it: v2_create_instance(module_dir) scans <module_dir>/banks."""
    print("\nHost API (v2 entry points):")
    tmp = tempfile.mkdtemp(prefix="tinyk_hostapi_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_v2_create.argtypes = [ctypes.c_char_p]
        lib.tinyk_v2_set.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
        lib.tinyk_v2_get.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        module_dir = os.path.join(tmp, "module")
        os.makedirs(os.path.join(module_dir, "banks"))
        dump = open(FACTORY, "rb").read()
        open(os.path.join(module_dir, "banks", "MicroKorgFactory.syx"), "wb").write(
            with_names(dump, {i: f"Name {i:03d}" for i in range(128)}))
        open(os.path.join(module_dir, "banks", "Odd 'Name' & Co.syx"), "wb").write(dump)

        def get(key):
            buf = ctypes.create_string_buffer(65536)
            n = lib.tinyk_v2_get(key.encode(), buf, len(buf))
            return buf.value.decode() if n >= 0 else None

        def put(key, val):
            lib.tinyk_v2_set(key.encode(), str(val).encode())

        check(lib.tinyk_v2_create(module_dir.encode()) == 1, "instance created")
        try:
            cp = json.loads(get("chain_params"))
            meta = {e["key"]: e for e in cp}
            ok = True
        except (TypeError, ValueError) as exc:
            cp, meta, ok = [], {}, False
            print("        chain_params:", exc)
        check(ok and len(cp) >= 30, f"chain_params is valid JSON ({len(cp)} params)")
        check(meta.get("bank_file", {}).get("options") == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"],
              f"Bank options are the file names (with JSON escaping): {meta.get('bank_file', {}).get('options')}")
        codes = [f"{s}{c}" for s in "AB" for c in range(1, 9)]
        prog = meta.get("patch", {})
        check(meta.get("category", {}).get("options", [None])[0] == "Trance" and len(meta["category"]["options"]) == 7
              and len(prog.get("options", [])) == 16 and prog.get("short_options") == codes,
              "Category has 7 named options (the vocoder row is not offered), Program 16 (short_options A1..B8)")
        check(prog.get("options") == [get(f"preset_name:{(i // 8) * 56 + i % 8}") for i in range(16)],
              f"Program options are the category's patch names: {prog.get('options', [])[:2]} ... {prog.get('options', [])[-1:]}")
        items = json.loads(get("bank_list") or "[]")
        check([i["label"] for i in items] == ["Built-in", "MicroKorgFactory", "Odd 'Name' & Co"] and [i["index"] for i in items] == [0, 1, 2],
              f"Banks page items: {items}")
        hier = json.loads(get("ui_hierarchy"))
        manifest = json.load(open(os.path.join(cal.ROOT, "src", "module.json"), encoding="utf-8"))
        # the engine serves the manifest's hierarchy with one of the Osc page's Control 1 / DWGS entries cut
        want = json.loads(json.dumps(manifest["capabilities"]["ui_hierarchy"]))
        osc_params = hier["levels"]["osc"]["params"]
        dwgs_on = any(p.get("key") == "dwgs_wave" for p in osc_params)
        want["levels"]["osc"]["params"] = [p for p in want["levels"]["osc"]["params"]
                                           if p.get("key") != ("osc1_ctrl1" if dwgs_on else "dwgs_wave")]
        if dwgs_on:
            want["levels"]["osc"]["knobs"][1] = "dwgs_wave"
        check(hier == want, "engine ui_hierarchy == module.json ui_hierarchy (one of Control 1 / DWGS on the Osc page)")
        levels = hier["levels"]
        # One page per section of the instrument (Perf, Osc, Filter, Amp, Mod, Effects), then the arpeggiator, then
        # Bank. Filter and Amp each carry their own envelope; the Osc page's second knob is Control 1, or the DWGS
        # selector while Wave 1 is DWGS (the manifest lists both entries, the engine serves one: checked below).
        pages = {"perf": ("Perf", ["category", "patch", "arp_on", "voice_mode", "timbre_edit", "voice_assign", "portamento",
                                   "timbre_balance"]),
                 "osc": ("Osc [L1]", ["wave1", "osc1_ctrl1", "osc1_ctrl2", "wave2", "sync_ring", "osc2_semi", "osc2_tune", "osc_mix"]),
                 "filter": ("Filter [L1]", ["filter_type", "cutoff", "resonance", "env_int", "attack1", "decay1", "sustain1", "release1"]),
                 "amp": ("Amp [L1]", ["noise_level", "level", "drive", "pan", "attack2", "decay2", "sustain2", "release2"]),
                 "mod": ("Mod", ["lfo1_rate", "lfo2_rate", "mod_wheel", "keytrack"]),
                 "fx": ("Effects", ["modfx_type", "modfx_speed", "chorus_mix", "delay_type", "delay_time", "delay_feedback",
                                    "delay_mix", "master_vol"]),
                 "arpset": ("Arp Settings", ["arp_type", "arp_range", "arp_resolution", "arp_gate", "arp_swing", "arp_latch",
                                             "arp_key_sync", "arp_target"]),
                 "steps": ("Arp Steps", [f"arp_step{n}" for n in range(1, 9)])}
        check([p.get("level") for p in levels["root"]["params"]] == ["perf", "osc", "filter", "amp", "mod", "fx", "arpset", "steps", "bank"]
              and levels["root"]["knobs"] == [],
              f"root is the preset browser with the page levels in order: {[p.get('level') for p in levels['root']['params']]}")
        check(all(levels[k]["name"] == name and levels[k]["knobs"] == knobs for k, (name, knobs) in pages.items()),
              "Perf / Osc / Filter / Amp / Mod / Effects / Arp Settings / Arp Steps pages hold their knobs (per-layer pages badged [L1])")
        help_doc = json.load(open(os.path.join(cal.ROOT, "src", "help.json"), encoding="utf-8"))
        help_pages = [c["title"] for c in next(c for c in help_doc["children"] if c["title"] == "Pages")["children"]]
        check(help_pages == [f"{i}: {levels[p['level']]['label']}" for i, p in enumerate(levels["root"]["params"], 1)],
              f"help.json lists the pages in the same order: {help_pages}")
        every = [k for _, knobs in pages.values() for k in knobs]
        check(len(every) == len(set(every)) and not {"bank_side", "program", "bank_file", "detune", "sub_level"} & set(every),
              "each control on one page; no A/B, Bank, Detune or Sub Level knob")
        check(meta["wave1"].get("options") == ["Saw", "Square", "Triangle", "Sine", "Vox", "DWGS", "Noise"]
              and meta["wave1"].get("short_options") == ["SAW", "SQR", "TRI", "SIN", "VOX", "DWG", "NZ"]
              and meta["wave2"].get("short_options") == ["SAW", "SQR", "TRI"]
              and meta["cutoff"].get("short_name") == ("L1.CUT" if get("voice_mode") == "1" else None),
              f"Wave 1/2 are enums named for the waveform; Layer 1 labels: {meta['cutoff'].get('short_name')!r} "
              f"(voice mode {get('voice_mode')}: L1.CUT in Layer, plain in Single)")
        missing = [k for k in every if k not in meta]
        check(not missing, f"chain_params describes every page knob (missing: {missing})")

        # Wave enums travel as indices (or names); Semi / Tune split detune; Level / Noise are per-timbre extras
        put("wave1", "3")
        put("wave2", "Square")
        w = [get("wave1"), get("wave2")]
        put("wave1", "0.0")           # a normalized value from a generic control
        check(w == ["3", "1"] and get("wave1") == "0", f"wave1 index 3 -> {w[0]}, wave2 'Square' -> {w[1]}, '0.0' -> {get('wave1')}")
        put("osc2_semi", "-7")
        put("osc2_tune", "25")
        st = [get("osc2_semi"), get("osc2_tune")]
        put("osc2_semi", "40")
        check(st == ["-7", "25"] and get("osc2_semi") == "24" and get("osc2_tune") == "0",
              f"Semi -7 / Tune +25 read back {st}; Semi clamps to {get('osc2_semi')} (the +-24 st range, so no tune above it)")
        put("level", "0.25")
        put("noise_level", "0.5")
        check(get("level") == "0.2500" and get("noise_level") == "0.5000", f"Level / Noise: {get('level')}, {get('noise_level')}")
        mw0 = get("mod_wheel")
        put("mod_wheel", "100")
        check(mw0 == "0" and get("mod_wheel") == "100" and meta["mod_wheel"].get("max") == 127
              and meta["mod_wheel"].get("short_name") == "MOD",
              f"Mod Wheel knob (MOD, 0..127): starts {mw0}, set 100 -> {get('mod_wheel')}")
        put("mod_wheel", "0")

        # Layer 2 in Layer mode: the per-layer page names and labels say L2, global ones stay plain
        check(get("is_loading") == "0", "no label change pending")
        put("voice_mode", "1")
        put("timbre_edit", "1")
        loading = [get("is_loading"), get("is_loading")]
        hier2 = json.loads(get("ui_hierarchy"))
        meta2 = {e["key"]: e for e in json.loads(get("chain_params"))}
        check(loading == ["1", "0"] and hier2["levels"]["osc"]["name"] == "Osc [L2]" and hier2["levels"]["perf"]["name"] == "Perf" and hier2["levels"]["fx"]["name"] == "Effects"
              and meta2["cutoff"].get("short_name") == "L2.CUT" and meta2["cutoff"].get("label") == "L2 Cutoff"
              and meta2["attack2"].get("short_name") == "L2.ATK" and meta2["voice_assign"].get("short_name") == "L2.VOIC" and "short_name" not in meta2["delay_mix"]
              and "short_name" not in meta2["patch"],
              f"Layer 2 edit: is_loading {loading}, page {hier2['levels']['osc']['name']!r}, "
              f"cutoff cell {meta2['cutoff'].get('short_name')!r}")
        put("level", "0.75")
        macros = ("cutoff", "resonance", "attack2", "release2")  # per-layer knobs on Filter and Amp
        put("timbre_edit", "0")
        t1_macros = [get(k) for k in macros]
        put("timbre_edit", "1")
        for k in macros:
            put(k, "0.3")
        t2_macros = [get(k) for k in macros]
        put("timbre_edit", "0")
        check(get("level") == "0.2500", f"Level edits the selected layer only (Layer 1 kept {get('level')})")
        check([get(k) for k in macros] == t1_macros and t2_macros == ["0.3000"] * 4,
              f"Cutoff, Resonance, Amp Atk / Rel edit the selected layer: L2 {t2_macros}, L1 kept {t1_macros}")
        put("voice_mode", "0")
        get("is_loading")             # the host takes the change back to Layer 1
        # Filter Type and Sync / Ring are option boxes; Sync / Ring in the hardware's order (off, ring, sync,
        # ring sync), which the engine remaps to its own (off, sync, ring, both)
        check(meta["filter_type"].get("short_options") == ["LPF24", "LPF12", "BPF12", "HPF12"]
              and meta["sync_ring"].get("short_options") == ["OFF", "RING", "SYNC", "R.SNC"]
              and meta["voice_mode"].get("short_options") == ["SNGL", "LAYR"],
              "Filter Type / Sync-Ring / Voice Mode option-box texts")
        # Single mode has one layer: Layer says N/A and the per-layer labels are plain; Layer mode names
        # the edited layer on the labels (L1.CUT / L2.CUT) and the sound-design pages' headers ([L1] / [L2])
        seen = {}
        for vm, te in (("0", "0"), ("0", "1"), ("1", "0"), ("1", "1")):
            put("voice_mode", vm)
            put("timbre_edit", te)
            changed = [get("is_loading"), get("is_loading")]
            m = {e["key"]: e for e in json.loads(get("chain_params"))}
            names = {k: v["name"] for k, v in json.loads(get("ui_hierarchy"))["levels"].items()}
            seen[vm + te] = (m["timbre_edit"].get("short_options"), m["cutoff"].get("short_name"),
                             m["attack1"].get("short_name"), m["drive"].get("label"), m["wave1"].get("short_name"),
                             names["osc"], names["filter"], names["amp"], names["perf"], changed)
        single = (["N/A", "N/A"], None, None, None, None, "Osc [L1]", "Filter [L1]", "Amp [L1]", "Perf")
        check(seen["00"][:-1] == single and seen["01"][:-1] == single and seen["01"][-1] == ["0", "0"],
              f"Single mode: Layer {seen['00'][0]}, plain labels, either stored edit choice: {seen['00'][:5]}")
        check(seen["10"][:-1] == (["L1", "L2"], "L1.CUT", "L1.FATK", "L1 Distortion", "L1.WV1", "Osc [L1]",
                                  "Filter [L1]", "Amp [L1]", "Perf") and seen["10"][-1] == ["1", "0"],
              f"Layer, Layer 1: {seen['10'][:-1]}; is_loading {seen['10'][-1]} (the Mode turn is a label change)")
        check(seen["11"][:-1] == (["L1", "L2"], "L2.CUT", "L2.FATK", "L2 Distortion", "L2.WV1", "Osc [L2]",
                                  "Filter [L2]", "Amp [L2]", "Perf") and seen["11"][-1] == ["1", "0"],
              f"Layer, Layer 2: {seen['11'][:-1]}; is_loading {seen['11'][-1]}")
        put("voice_mode", "0")
        put("timbre_edit", "0")
        get("is_loading")
        # Voice (Mono / Poly / Unison) is the layer's polyphony: by name or index, one per layer
        va_meta = {e["key"]: e for e in json.loads(get("chain_params"))}["voice_assign"]
        put("voice_assign", "Unison")
        va = [get("voice_assign")]
        put("voice_mode", "1")
        put("timbre_edit", "1")
        put("voice_assign", "Mono")
        va += [get("voice_assign")]
        put("timbre_edit", "0")
        va += [get("voice_assign")]
        put("voice_mode", "0")
        check(va_meta.get("options") == ["Mono", "Poly", "Unison"] and va_meta.get("short_options") == ["MONO", "POLY", "UNIS"]
              and va == ["2", "0", "2"],
              f"Voice assign: Mono / Poly / Unison options, Layer 2 Mono leaves Layer 1 Unison: {va}")
        put("voice_assign", "1")
        put("filter_type", "BPF12")
        ft = get("filter_type")
        put("sync_ring", "R.SNC")
        sr = [get("sync_ring")]
        put("sync_ring", "1")
        sr.append(get("sync_ring"))
        check(ft == "2" and sr == ["3", "1"], f"by name / index: BPF12 -> {ft}, R.SNC -> {sr[0]}, Ring (1) -> {sr[1]}")
        put("bank_file", "1")
        seen = {}
        for idx in (9, 2, 23, 0, 17):   # factory programs with hardware ring, sync, ring sync; BPF12, HPF12
            put("preset", str(idx))
            seen[idx] = (get("sync_ring"), get("filter_type"))
        check([seen[i][0] for i in (9, 2, 23)] == ["1", "2", "3"] and seen[0][1] == "2" and seen[17][1] == "3",
              f"decoded programs report the hardware's mode: {seen}")
        put("bank_file", "0")
        get("is_loading")             # the host takes the bank / category change

        # Program labels follow Category and Bank; is_loading answers "1" once per unreported change so the
        # host re-reads chain_params on the 1 -> 0 edge
        loading0 = get("is_loading")
        put("bank_file", "1")
        put("category", "Retro")      # by name
        loading = [get("is_loading"), get("is_loading")]
        check(loading0 == "0" and loading == ["1", "0"], f"is_loading after Bank/Category change: {loading0} then {loading}")
        prog = {e["key"]: e for e in json.loads(get("chain_params"))}["patch"]
        check(prog["options"][11] == "B.64 Name 107" and get("is_loading") == "0",
              f"re-read Program options name the new category and bank: {prog['options'][11]!r}")
        vm_before = get("voice_mode")
        put("patch", "11")            # by index: B4
        relabel = get("is_loading")   # only the timbre labels can change (a program in the other voice mode)
        check(get("preset") == str(56 + 5 * 8 + 3) and get("category") == "5" and get("patch") == "11"
              and relabel == ("0" if get("voice_mode") == vm_before else "1"),
              f"Category Retro + Program B4 -> preset {get('preset')} (expected {56 + 5 * 8 + 3}, ordinal of slot 107); "
              f"is_loading {relabel} (voice mode {vm_before} -> {get('voice_mode')})")
        check(get("preset_name") == "B.64 Name 107", f"name from the selected bank: {get('preset_name')!r}")
        put("patch", "A.62 Name 041")
        check(get("preset") == str(5 * 8 + 1), f"Program by its label -> preset {get('preset')}")
        put("patch", "A1")
        check(get("preset") == str(5 * 8), f"Program A1 by name -> preset {get('preset')}")
        put("preset", "1")
        check(get("preset") == "1", f"preset browser index '1' -> preset {get('preset')} (was 127 before the fix)")
        put("preset", "127")
        check(get("preset") == "111" and get("category") == "6" and get("patch") == "15",
              "preset 127 clamps to the last of the 112 programs: Category SE/Hit, Program B8")
        put("bank_file", "MicroKorgFactory")
        check(get("bank_file") == "1" and get("bank_file_name") == "MicroKorgFactory", "bank by name")

        # Slot state (the host's autosave / boot restore): edits survive a round trip through another program
        put("preset", "20")
        put("voice_mode", "1")
        put("timbre_edit", "1")
        put("cutoff", "0.123")
        put("level", "0.3")
        put("timbre_edit", "0")
        put("resonance", "0.777")
        put("delay_mix", "0.42")
        before = {k: get(k) for k in ("bank_file_name", "preset", "voice_mode", "resonance", "delay_mix", "level")}
        state = get("state")
        try:
            doc = json.loads(state)
        except ValueError:
            doc = {}
        check(doc.get("tinyk_state") == 1 and doc.get("bank") == "MicroKorgFactory" and doc.get("preset") == 20
              and len(doc.get("params", [])) == 35 and len(doc.get("extra2", [])) == 37,
              f"state is JSON ({len(state)} bytes): bank, preset, params, extras")
        put("bank_file", "0")
        put("preset", "99")
        put("state", state)
        after = {k: get(k) for k in before}
        put("timbre_edit", "1")
        t2 = (get("cutoff"), get("level"))
        check(after == before and t2 == ("0.1230", "0.3000"), f"state restores bank, program and edits: {after}, T2 {t2}")
        # A state saved before Osc 1 Ctrl 1 / 2 were decoded (24 extras) still restores its extras
        old_doc = dict(doc)
        old_doc["extra2"] = doc["extra2"][:24]
        old_doc["extra2"][2] = 0.4  # Timbre 2 level
        put("preset", "99")
        put("state", json.dumps(old_doc))
        put("timbre_edit", "1")
        check(get("level") == "0.4000" and get("preset") == "20", f"24-value extras (older state) restore: level {get('level')}")
        put("preset", "5")
        put("state", "{\"tinyk_state\":1,\"preset\":7,\"params\":[1,2]}")
        check(get("preset") == "7" and get("bank_file_name") == "Built-in", "a partial state keeps the program's values")
        put("state", "garbage")
        check(get("preset") == "7", "a state that is not TinyK's is ignored")

        # The Arp knob: a program loads its stored arp setting; the knob overrides it; the slot state keeps it
        put("bank_file", "0")
        put("preset", "8")  # A.21: arp on
        a21_on = get("arp_on")
        put("preset", "2")  # A.13: arp off
        a13_on = get("arp_on")
        put("arp_on", "On")
        knob_on = get("arp_on")
        st = json.loads(get("state"))
        put("preset", "2")
        reloaded = get("arp_on")
        put("state", json.dumps(st))
        check(a21_on == "1" and a13_on == "0" and knob_on == "1" and st.get("arp_on") == 1 and reloaded == "0"
              and get("arp_on") == "1",
              f"Arp: programs load their own (A.21 {a21_on}, A.13 {a13_on}); knob On -> {knob_on}; saved in the state and restored")
        meta_arp = {p["key"]: p for p in json.loads(get("chain_params"))}.get("arp_on", {})
        check(meta_arp.get("options") == ["Off", "On"] and "arp_on" in manifest["capabilities"]["ui_hierarchy"]["levels"]["perf"]["knobs"],
              "Arp knob on the Perf page, an Off / On enum in chain_params")
        put("arp_on", "0")

        # Arp Steps: 1 = play, 0 = rest; starts from the program's stored pattern, edits are live and saved
        put("preset", "8")  # A.21: pattern 0x52 (steps 2, 5, 7 rest), 8 steps
        stored = [get(f"arp_step{n}") for n in range(1, 9)]
        put("arp_step1", "Rest")
        put("arp_step2", "1")
        edited = [get(f"arp_step{n}") for n in range(1, 9)]
        st = json.loads(get("state"))
        put("preset", "8")
        reloaded = [get(f"arp_step{n}") for n in range(1, 9)]
        put("state", json.dumps(st))
        restored = [get(f"arp_step{n}") for n in range(1, 9)]
        meta_st = {p["key"]: p for p in json.loads(get("chain_params"))}.get("arp_step3", {})
        check(stored == list("10110101") and edited == list("01110101") and st.get("arp_pattern") == 0x51
              and reloaded == stored and restored == edited and meta_st.get("options") == ["Rest", "Play"],
              f"Arp Steps: A.21 loads {''.join(stored)}; Step 1 Rest / Step 2 Play -> {''.join(edited)} (pattern "
              f"0x{st.get('arp_pattern', 0):02X} in the state); a program reload restores the stored steps, the state the edit")
        # the steps draw as canvas.js's LEDs: a custom viz on each step (served and in module.json), fed by arp_playhead
        viz = {"kind": "custom:tinyk_step", "extra_keys": ["arp_playhead"]}
        cp_now = {p["key"]: p for p in json.loads(get("chain_params"))}
        inline = manifest["capabilities"]["ui_hierarchy"]["levels"]["steps"]["params"]
        ph = cp_now.get("arp_playhead", {})
        check(all(cp_now.get(f"arp_step{n}", {}).get("viz") == viz for n in range(1, 9))
              and all(p.get("viz") == viz for p in inline)
              and ph.get("type") == "string" and ph.get("access") == "read" and get("arp_playhead") == "0,8"
              and os.path.isfile(os.path.join(cal.ROOT, "src", "canvas.js")),
              f"Arp Steps LEDs: custom:tinyk_step on the 8 steps (chain_params and module.json), read-only arp_playhead "
              f"({get('arp_playhead')!r} with no keys held), src/canvas.js present")
        st1 = dict(json.loads(get("state")), arp_length=1, arp_pattern=0)  # an MS2000-style 1-step pattern
        put("state", json.dumps(st1))
        st64 = json.loads(get("state"))
        put("arp_step4", "Rest")
        st64b = json.loads(get("state"))
        check(st64.get("arp_length") == 1 and st64b.get("arp_length") == 4 and get("arp_step4") == "0"
              and get("arp_step2") == "1" and get("arp_step3") == "1",
              f"Step 4 past a {st64.get('arp_length')}-step pattern extends it to {st64b.get('arp_length')} steps, steps between play")
        # Arp Settings: A.21's stored values, set by option name or index, saved and restored
        put("preset", "8")
        keys8 = ["arp_type", "arp_range", "arp_resolution", "arp_gate", "arp_swing", "arp_latch", "arp_key_sync", "arp_target"]
        a21 = [get(k) for k in keys8]
        for k, v in zip(keys8, ["ALT1", "3", "1/8", "55", "-40", "Off", "0", "Layer 2"]):
            put(k, v)
        edited8 = [get(k) for k in keys8]
        st8 = json.loads(get("state"))
        put("preset", "8")
        back8 = [get(k) for k in keys8]
        put("state", json.dumps(st8))
        restored8 = [get(k) for k in keys8]
        meta8 = {p["key"]: p for p in json.loads(get("chain_params"))}
        check(a21 == ["0", "1", "1", "80", "0", "1", "1", "1"] and edited8 == ["2", "3", "3", "55", "-40", "0", "0", "2"]
              and back8 == a21 and restored8 == edited8 and st8.get("arp_type") == 2 and st8.get("arp_swing") == -40
              and meta8.get("arp_type", {}).get("options") == ["UP", "DOWN", "ALT1", "ALT2", "RANDOM", "TRIGGER"]
              and meta8.get("arp_swing", {}).get("min") == -100 and meta8.get("arp_target", {}).get("short_options") == ["BOTH", "L1", "L2"],
              f"Arp Settings: A.21 {a21} -> set by name {edited8}, saved in the state; the program restores its own, the state the edits")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def multi_instance():
    """Two slots each running TinyK: one dsp.so, two v2 instances that must share nothing."""
    print("\nTwo instances (two slots):")
    tmp = tempfile.mkdtemp(prefix="tinyk_multi_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_v2_create_n.argtypes = [ctypes.c_int, ctypes.c_char_p]
        lib.tinyk_v2_set_n.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_char_p]
        lib.tinyk_v2_get_n.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_v2_midi_n.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_v2_render_n.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int16), ctypes.c_int]
        module_dir = os.path.join(tmp, "module")
        os.makedirs(os.path.join(module_dir, "banks"))
        shutil.copy(FACTORY, os.path.join(module_dir, "banks", "MicroKorgFactory.syx"))

        def get(n, key):
            buf = ctypes.create_string_buffer(65536)
            return buf.value.decode() if lib.tinyk_v2_get_n(n, key.encode(), buf, len(buf)) >= 0 else None

        def put(n, key, val):
            lib.tinyk_v2_set_n(n, key.encode(), str(val).encode())

        def midi(n, *msg):
            lib.tinyk_v2_midi_n(n, bytes(msg), len(msg))

        def peak(n, blocks=40):
            out = (ctypes.c_int16 * 256)()
            top = 0
            for _ in range(blocks):
                lib.tinyk_v2_render_n(n, out, 128)
                top = max(top, max(abs(v) for v in out))
            return top

        check(lib.tinyk_v2_create_n(0, module_dir.encode()) == 1 and lib.tinyk_v2_create_n(1, module_dir.encode()) == 1,
              "two instances created")
        keys = ("preset", "bank_file_name", "cutoff", "voice_mode", "timbre_edit", "modfx_type", "arp_on", "arp_step1")
        fresh = {k: get(1, k) for k in keys}
        state1 = get(1, "state")
        chain1 = get(1, "chain_params")
        put(0, "bank_file", "MicroKorgFactory")
        put(0, "preset", "20")
        put(0, "cutoff", "0.123")
        put(0, "voice_mode", "1")
        put(0, "timbre_edit", "1")
        put(0, "modfx_type", "2")
        put(0, "arp_on", "1")
        put(0, "arp_step1", "Rest")
        edited = {k: get(0, k) for k in keys}
        check({k: get(1, k) for k in keys} == fresh and edited != fresh,
              f"edits on slot 1 leave slot 2 alone: slot 1 {edited}, slot 2 {fresh}")
        check(get(1, "state") == state1 and get(1, "chain_params") == chain1 and get(0, "state") != state1,
              "slot 2's state and chain_params unchanged (bank, program, labels)")
        load0 = [get(0, "is_loading"), get(0, "is_loading")]
        check(load0 == ["1", "0"] and get(1, "is_loading") == "0",
              f"label changes are reported to the slot that made them only: slot 1 {load0}, slot 2 {get(1, 'is_loading')}")

        # Audio: a note on slot 1 sounds on slot 1 only; a note off on slot 2 does not stop it
        put(0, "arp_on", "0")
        put(0, "voice_mode", "0")
        put(1, "preset", "0")
        quiet = [peak(0, 4), peak(1, 4)]
        midi(0, 0x90, 60, 100)
        sounding = [peak(0), peak(1)]
        midi(1, 0x80, 60, 0)
        midi(1, 0xB0, 123, 0)
        held = peak(0)
        check(quiet == [0, 0] and sounding[0] > 1000 and sounding[1] == 0 and held > 1000,
              f"a note on slot 1 sounds there only (peaks {sounding}); slot 2's note off / all notes off leave it ({held})")
        midi(1, 0x90, 64, 100)
        both = [peak(0), peak(1)]
        check(both[0] > 1000 and both[1] > 1000, f"both slots play at once: peaks {both}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    if not os.path.exists(FACTORY):
        sys.exit(f"missing {FACTORY}")
    dump = open(FACTORY, "rb").read()
    dump = with_names(dump, {i: "" for i in range(128)})  # the scan / label checks start from an unnamed bank
    tmp = tempfile.mkdtemp(prefix="tinyk_banks_")
    try:
        lib = ctypes.CDLL(cal.build_library(tmp))
        lib.tinyk_bank_scan.argtypes = [ctypes.c_char_p]
        lib.tinyk_bank_name.restype = ctypes.c_char_p
        fptr = ctypes.POINTER(ctypes.c_float)
        lib.tinyk_bank_preset.argtypes = [ctypes.c_int, ctypes.c_int, fptr, fptr, fptr, ctypes.c_char_p, ctypes.c_int]
        lib.tinyk_select.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p, ctypes.c_int]

        banks = os.path.join(tmp, "banks")
        os.makedirs(banks)
        open(os.path.join(banks, "zeta.syx"), "wb").write(dump)                                # bank 3
        open(os.path.join(banks, "Alpha.syx"), "wb").write(dump)                               # bank 1
        open(os.path.join(banks, "named.SYX"), "wb").write(with_names(dump, {0: "A.11 Trancey", 1: "AcidSaw", 64: "  Spaced  "}))  # bank 2
        open(os.path.join(banks, "junk.syx"), "wb").write(b"\xF0\x42\x30\x58\x50" + b"\x00" * 100 + b"\xF7")  # too short
        single = os.path.join(cal.REF_DIR, "mk_a11.syx")
        if os.path.exists(single):
            shutil.copy(single, os.path.join(banks, "single_program.syx"))                      # program dump, not a bank
        open(os.path.join(banks, "readme.txt"), "w").write("not a bank")
        program_msg = open(single, "rb").read() if os.path.exists(single) else b"\xF0\x42\x30\x58\x40\x00\xF7"
        open(os.path.join(banks, "multi.syx"), "wb").write(program_msg + dump)                     # bank after another message
        open(os.path.join(banks, "truncated.syx"), "wb").write(dump[:20000] + b"\xF7")             # cut short
        open(os.path.join(banks, "big.syx"), "wb").write(bytes(np.random.default_rng(1).integers(0, 256, 70000, dtype=np.uint8)))
        open(os.path.join(banks, "empty.syx"), "wb").write(b"")

        print("Scanning:")
        n = lib.tinyk_bank_scan(banks.encode())
        names = [lib.tinyk_bank_name(b).decode() for b in range(1, lib.tinyk_bank_count() + 1)]
        check(n == 4 and names == ["Alpha", "multi", "named", "zeta"],
              f"4 banks loaded in alphabetical order; single-program, truncated, random, empty, .txt skipped: {names}")

        def preset(b, idx):
            t1 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            t2 = np.zeros(len(TIMBRE_FIELDS), np.float32)
            fx = np.zeros(len(FX_FIELDS), np.float32)
            label = ctypes.create_string_buffer(32)
            vm = lib.tinyk_bank_preset(b, idx, t1.ctypes.data_as(fptr), t2.ctypes.data_as(fptr), fx.ctypes.data_as(fptr), label, 32)
            return vm, np.concatenate([t1, t2, fx]), label.value.decode()

        print("Parity with presets.h (built-in bank):")
        worst, mode_ok = 0.0, True
        for idx in range(128):
            vm0, v0, _ = preset(0, idx)
            vm1, v1, _ = preset(1, idx)
            worst = max(worst, float(np.abs(v0 - v1).max()))
            mode_ok &= vm0 == vm1
        check(worst <= 1e-6 and mode_ok, f"all 128 presets match (largest difference {worst:.1e}, voice modes equal: {mode_ok})")

        print("Names:")
        check(preset(1, 0)[2] == "A.11" and preset(1, 127)[2] == "B.88", f"unnamed dump labels by code: {preset(1, 0)[2]!r}, {preset(1, 127)[2]!r}")
        labels = [preset(3, i)[2] for i in (0, 1, 2, 64)]
        check(labels == ["A.11 Trancey", "A.12 AcidSaw", "A.13", "B.11 Spaced"], f"stored names used: {labels}")

        print("Selection through the parameter API:")
        buf = ctypes.create_string_buffer(16)
        lib.tinyk_render.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_double, ctypes.c_double, fptr, ctypes.c_int]
        out = np.zeros(2 * 2000, np.float32)
        lib.tinyk_render(0, 60, 0.01, 0.02, out.ctypes.data_as(fptr), 2000)  # initialises the test instance

        def sel(key, val):
            lib.tinyk_select(key.encode(), val.encode(), buf, 16)
            return int(buf.value)
        check(sel("bank_side", "0") == 0 and sel("program", "27") == 14, "A.27 -> preset 14")
        check(sel("program", "29") == 16, "stepping 28 -> 29 snaps to 31 (preset 16)")
        check(sel("program", "30") == 15, "stepping 31 -> 30 snaps to 28 (preset 15)")
        check(sel("bank_side", "1") == 79, "switching to bank B keeps the program: B.28 -> preset 79")
        check(sel("program", "88") == 119 and sel("program", "99") == 119,
              "program 88 / out of range clamps to B.78 (slot 119): the vocoder row is not offered")
        check(sel("bank_file", "3") == 119, "bank_file switch keeps the current program")
        check(sel("bank_file", "9") == 119, "bank_file beyond the loaded banks clamps")
        user_banks(fptr)
        host_api()
        vocoder_banks()
        multi_instance()
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"\n{'ALL PASSED' if not FAILS else f'{len(FAILS)} FAILED'}")
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
